module.exports = {
  GOOGLE_ANALYTICS_KEY: "",
  FIREBASE_URL: "",
  KEEN_PROJECT_ID: "",
  KEEN_WRITE_KEY: "",
  AIRBRAKE_PRODUCT_ID: "",
  AIRBRAKE_PRODUCT_KEY: "",
  AWS_ACCESS_KEY_ID: "",
  AWS_SECRET_ACCESS_KEY: "",
  LOCAL_STORAGE_KEY: "smartpickingsuid",
  LOCKDOWN_KEY: "044b00002ab4eddd0033b0de4544bbe7",
  MAILCHIMP_API_KEY: "",
  MAILCHIMP_LIST_ID: "",
};
